name: Build Servers A and B

on:
  workflow_dispatch: 
  # push:
  #   tags:
  #    - 'v\d+\.\d+\.\d+'
  #    - 'v[0-9]{8}.[0-9]{4}'
  #schedule:
    # Run at 08:00 AM MDT every Monday
    # Adjusting for UTC, which is typically 6 hours ahead of MDT
    #- cron: '0 14 * * 1'  # 14:00 UTC is 8:00 AM MDT during Daylight Saving Time

  #  - cron: '4 5 * * 5'  # 4:46 AM UTC on Tuesday, which is 10:46 PM CST on Monday

jobs:

  sync_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: "${{ steps.settag.outputs.TAG_NAME }}"
    steps:
      - name: Create git tag from Timestamp
        id: settag
        run: |
          tag=$(date -u +"v%Y%m%d.%H%M")
          echo $tag
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Push tag
        env:
          REPOA_PAT: ${{ secrets.REPOA_PAT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git clone https://github.com/wporta/serverA.git
          cd serverA
          git tag $TAG_NAME
          git push https://wporta:${REPOA_PAT}@github.com/wporta/serverA.git --tags
        

          # - name: Setup Git Config
      #   run: |
      #    git config user.name "github-actions[bot]"
      #    git config user.email "${{ github.actor }}@users.noreply.github.com"
      # - name: Extract the tag name
      #   id: extract_tag
      #   run: echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV

      # - name: Push the new tag
      #   run: |
      #     git tag -a ${{ github.ref_name }} -m '${{ github.ref_name }}'
      #     git push origin --tags

      # - name: Push tag to serverA
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN
      #   run: |
      #     TAG_NAME=${{ env.tag }}
      #     REPO_A_OWNER=${{ github.repository_owner }} # Automatically gets the repo owner
      #     REPO_A_NAME=serverB

      #     # Clone serverA
      #     echo ${GITHUB_TOKEN}
      #     git clone https://${REPO_A_OWNER}:${GITHUB_TOKEN}@github.com/${REPO_A_OWNER}/${REPO_A_NAME}
      #     cd ${REPO_A_NAME}

      #     # Configure git
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"

      #     # Create and push the tag to serverA
      #     git tag $TAG_NAME
      #     git push origin $TAG_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: sync_tag
    steps:
      - name: Deploy
        run: |
          echo "Deploy Apps with tag: ${{ needs.sync_tag.outputs.tag_name }}"
