# This is a build workflow. It should be the entry point.

name: Build Project

on:
  workflow_dispatch:

jobs:
#  buildApi:
#    name: Build API Project
#    runs-on: ubuntu-latest
#    steps:
#      - name: Matrix Test
#        id: set-matrix
#        run: |
#          echo "::set-output name=matrix::server1 server2"
#    outputs:
#      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  echo-each-server:
    name: Echo to each server
    #needs: buildApi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #path: ${{ fromJson(needs.buildApi.outputs.matrix) }}
        path: ["server1", "server2", "server3"]
    steps:
      - name: Echo
        run: |
          echo ${{ matrix.path }}


