# This is a build workflow. It should be the entry point.

name: Build and Deploy API and WEB Projects

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging, alpha, beta, production)??'
        required: true
        #default: 'staging'
        type: choice
        options:
          - staging
          - alpha
          - beta
          - production


jobs:
  buildApi:
    name: Build API
    uses: ./.github/workflows/build-api.yml

  buildWeb:
    name: Build WEB
    uses: ./.github/workflows/build-web.yml

  # Executing different jobs depending on the releaseType
  deployToStaging:
    if: github.event.inputs.releaseType == 'staging'
    name: ${{ matrix.minion }}
    strategy:
      matrix:
        minion: [staging-1, staging-2, staging-3, staging-4, staging-5] # We should get a list of all minions
    uses: ./.github/workflows/deploy.yml
    with:
      minion: ${{ matrix.minion }}

  deployToAlpha:
    if: github.event.inputs.releaseType == 'alpha'
    name: ${{ matrix.minion }}
    strategy:
      matrix:
        minion: [alpha-1, alpha-2, alpha-3, alpha-4, alpha-5] # We should get a list of all minions
    uses: ./.github/workflows/deploy.yml
    with:
      minion: ${{ matrix.minion }}

  deployToBeta:
    if: github.event.inputs.releaseType == 'beta'
    name: ${{ matrix.minion }}
    strategy:
      matrix:
        minion: [beta-1, beta-2, beta-3, beta-4, beta-5] # We should get a list of all minions
    uses: ./.github/workflows/deploy.yml
    with:
      minion: ${{ matrix.minion }}

  deployToProd:
    if: github.event.inputs.releaseType == 'production'
    name: ${{ matrix.minion }}
    strategy:
      matrix:
        minion: [prod-1, prod-2, prod-3, prod-4, prod-5, prod-6, prod-7, prod-8, prod-9, prod-10] # We should get a list of all minions
    uses: ./.github/workflows/deploy.yml
    with:
      minion: ${{ matrix.minion }}


