name: Build Servers A and B

on:
  workflow_dispatch: 

jobs:
  buildServerA:
    uses: wporta/serverA/.github/workflows/serverA.yml@main

  buildServerB:
    uses: wporta/serverB/.github/workflows/serverB.yml@main


  deploy:
    runs-on: ubuntu-latest
    needs: [buildServerA, buildServerB]
    steps:
      - name: Deploy
        run: echo "Deploy Apps"
