# This is a build workflow. It should be the entry point.

name: Build Project

on:
  workflow_dispatch:

jobs:
  buildApi:
    name: Build API
    uses: ./build-api.yml

  buildWeb:
    name: Build WEB
    uses: ./build-web.yml
  
  deployToMinions:
    name: Echo to Minions
    strategy:
      matrix:
        minion: [minion-1, minion-2, minion-3, minion-4, minion-5, minion-6, minion-7, minion-8, minion-9, minion-10] # We should get a list of all minions
    uses: ./deploy.yml
    with:
      minion: ${{ matrix.minion }}


