name: Deploy API and Web Projects

on:
  workflow_call: 
    inputs:
      minion:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Minions
        run: |
          echo "Deploying projects to minion: ${{ inputs.minion }}"