name: Building with Reusable Workflows

on:
  workflow_dispatch: 

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Create git tag from Timestamp
        id: settag
        run: |
          tag=$(date -u +"v%Y%m%d.%H%M")
          echo $tag
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

    outputs:
      sharedVal: ${{ env.TAG_NAME }}

  build-server-A:
    name: Build Server A
    needs: create_tag
    uses: wporta/serverA/.github/workflows/build.yml@main
    env:
          REPOA_PAT: ${{ secrets.REPOA_PAT }}
    with:
      tag: ${{ needs.create_tag.outputs.sharedVal }}
      repo_pat: ${{ env.REPOA_PAT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-server-A
    steps:
      - name: Deploying
        run: |
          echo "Deploying"
          sleep 1m
          echo "Done Deploying"
